apiVersion: v1
kind: Service
metadata:
  name: vishnu-cicd-service
spec:
  type: NodePort
  selector:
    app: cicd-app
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 31000 # ఈసారి బ్రౌజర్ లో ఓపెన్ చేయడానికి 31000 పోర్ట్ వాడుతున్నాం బాస్
