name: Node App CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Deploy to Azure VM Kubernetes via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22
          script: |
          cd ~/node-emp-cicd
          echo "1. Pulling latest code from GitHub..."
          git pull origin main

          echo "2. Building Docker Image inside Minikube..."
          # ఇక్కడ మనం డైరెక్ట్ గా మినికూబ్ లోపలికే ఇమేజ్ ని పంపుతున్నాం
          eval $(minikube -p minikube docker-env)
          docker build -t vishnu-emp-app:latest .

          echo "3. Resetting Docker path back to Normal..."
          # ఇది మన టెర్మినల్ దారిని మళ్లీ నార్మల్ ఉబుంటు కి తిప్పుతుంది (దీనివల్ల నెట్‌వర్క్ ఎర్రర్ రాదు)
          eval $(minikube -p minikube docker-env -u)

          echo "4. Deploying Manifests..."
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

          echo "CI/CD Pipeline Completed Successfully! 🚀🔥"

