name: Node App CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Deploy to Azure VM Kubernetes via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22
        script: |
          cd ~/node-emp-cicd
          echo "1. Pulling latest code from GitHub..."
          git pull origin main

          echo "2. Pointing terminal to Minikube Docker..."
          eval $(minikube -p minikube docker-env)

          echo "3. Automatically building new Docker Image..."
          docker build -t vishnu-emp-app:latest .

          echo "4. Automatically applying Kubernetes Manifests..."
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

          echo "CI/CD Pipeline Completed Successfully! 🚀🔥"
